spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 192.168.3.58
    port: 6379

server:
  servlet:
    context-path: /sell

# logback 在该文件下可以做简单配置，详细配置可以使用 logback-spring.xml 文件
# logging:
#   # pattern:
#     # console: "%d - %msg%n" # 日期 - 信息\n
#   file:
#     name: ./log/sell.log
#   level:
#     root: info


wechat:
  mpAppId: wx5491f7ad52c421aa
  mpAppSecret: appSecret
  mchId: mchId
  mchKey: mchKey
  keyPath: /xxx/xxx/xx.p12 # 证书路径
  notifyUrl: http://localhost:8080/sell/pay/notify # 支付通知地址

logging:
  level:
    com.example.demo.entity.mapper: trace